-- Phase 1 subset of the legacy mallRN_* schema.
-- Source of truth: shoppingmall_php/install/install_post.php (CREATE TABLE statements),
-- copied verbatim (minus PHP string escaping) for the tables the Home page vertical
-- slice reads: configuration, goods, cate, goods_cate, goods_option, banner, popup,
-- exhibition, exhibition_goods, cate_matching.
-- The remaining ~60 tables (member/order/board/vendor/coupon/mileage/...) are added
-- in later phases as each feature is ported.

CREATE TABLE mallRN_banner (
 `uid` int unsigned NOT NULL AUTO_INCREMENT COMMENT '고유값',
 `name` varchar(100) NOT NULL default '' COMMENT '배너 이름',
 `code` varchar(10) NOT NULL default '' COMMENT '배너 코드(스킨 제작시 설정된 코드, 출력 위치에 사용)',
 `image1` varchar(100) NOT NULL default '' COMMENT '배너 이미지',
 `link1` varchar(250) NOT NULL default '' COMMENT '이동 url',
 `status` int unsigned NOT NULL default '0' COMMENT '상태 0(사용), 1(사용안함)',
 `target` int unsigned NOT NULL default '0' COMMENT '링크 이동 0(현재창), 1(새창)',
 `s_date` datetime default '1000-01-01 00:00:00' COMMENT '배너 시작시간',
 `e_date` datetime default '1000-01-01 00:00:00' COMMENT '배너 종료시간',
 `sequence` int unsigned NOT NULL default '0' COMMENT '노출 순서',
 `moddate` int unsigned NOT NULL default '0' COMMENT '수정일',
 `signdate` int unsigned NOT NULL default '0' COMMENT '등록일',
  PRIMARY KEY  (`uid`)
) DEFAULT CHARSET=utf8 COMMENT='배너 정보';

CREATE TABLE mallRN_mobile_banner (
 `uid` int unsigned NOT NULL AUTO_INCREMENT COMMENT '고유값',
 `name` varchar(100) NOT NULL default '' COMMENT '배너 이름',
 `code` varchar(10) NOT NULL default '' COMMENT '배너 코드',
 `image1` varchar(100) NOT NULL default '' COMMENT '배너 이미지',
 `link1` varchar(250) NOT NULL default '' COMMENT '이동 url',
 `status` int unsigned NOT NULL default '0' COMMENT '상태 0(사용), 1(사용안함)',
 `target` int unsigned NOT NULL default '0' COMMENT '링크 이동 0(현재창), 1(새창)',
 `s_date` datetime default '1000-01-01 00:00:00' COMMENT '배너 시작시간',
 `e_date` datetime default '1000-01-01 00:00:00' COMMENT '배너 종료시간',
 `sequence` int unsigned NOT NULL default '0' COMMENT '노출 순서',
 `moddate` int unsigned NOT NULL default '0' COMMENT '수정일',
 `signdate` int unsigned NOT NULL default '0' COMMENT '등록일',
  PRIMARY KEY  (`uid`)
) DEFAULT CHARSET=utf8 COMMENT='모바일 배너 정보';

CREATE TABLE `mallRN_cate` (
	`uid` int unsigned NOT NULL auto_increment COMMENT '고유값',
	`cate` bigint unsigned NOT NULL default '0' COMMENT '상품분류번호',
	`cate_name` varchar(60) NOT NULL default '' COMMENT '상품분류명',
	`cate_dep` tinyint unsigned NOT NULL default '0' COMMENT '상품분류 단계 1(1차분류), 2(2차분류), 3(3차분류), 4(4차분류)',
	`cate_parent` bigint unsigned NOT NULL default '0' COMMENT '상위 상품분류번호',
	`cate_sub` tinyint unsigned NOT NULL default '1' COMMENT '하위분류 유무 0(없음), 1(있음)',
	`used` tinyint unsigned NOT NULL default '1' COMMENT '사용여부 0(사용안함), 1(사용함)',
	`sequence` int unsigned NOT NULL default '0' COMMENT '상품분류 노출 순서',
	`access_type` tinyint unsigned NOT NULL default '0' COMMENT '상품분류 접근권한 0(전체), 1(회원만), 2(특정회원등급만)',
	`access_level` varchar(250) NOT NULL default '' COMMENT '상품분류 접근 회원등급 (access_type값이 2일 경우)',
	`matching` varchar(100) NOT NULL default '' COMMENT '상품분류 매칭문구 (상품일괄 등록시 사용)',
	`image1` varchar(100) NOT NULL default '' COMMENT '상품분류 이미지#1',
	`image2` varchar(100) NOT NULL default '' COMMENT '상품분류 이미지#2',
	`image3` varchar(100) NOT NULL default '' COMMENT '상품분류 이미지#3',
  PRIMARY KEY  (`uid`),
  KEY `cate` (`cate`)
) DEFAULT CHARSET=utf8 COMMENT='상품분류 설정 정보';

CREATE TABLE `mallRN_cate_matching` (
	`uid` int unsigned NOT NULL auto_increment COMMENT '고유값',
	`vendor` varchar(50) NOT NULL default '' COMMENT '판매사 아이디',
	`cate` bigint unsigned NOT NULL default '0' COMMENT '상품분류번호',
	`matching` varchar(100) NOT NULL default '' COMMENT '상품분류 매칭문구 (상품일괄 등록시 사용)',
  PRIMARY KEY  (`uid`),
  KEY `cate` (`cate`)
) DEFAULT CHARSET=utf8 COMMENT='상품분류 매칭설정 정보';

CREATE TABLE `mallRN_configuration` (
	`uid` int unsigned NOT NULL AUTO_INCREMENT COMMENT '고유값',
	`basic_url` varchar(100) NOT NULL default '' COMMENT '쇼핑몰 주소',
	`basic_name` varchar(50) NOT NULL default '' COMMENT '쇼핑몰명',
	`basic_admin` varchar(50) NOT NULL default '' COMMENT '관리자명',
	`basic_email` varchar(100) NOT NULL default '' COMMENT '관리자 이메일 주소',
	`basic_cs_time1` varchar(50) NOT NULL default '' COMMENT '고객센터 운영시간(평일)',
	`basic_cs_time2` varchar(50) NOT NULL default '' COMMENT '고객센터 운영시간(토요일)',
	`basic_cs_time3` varchar(50) NOT NULL default '' COMMENT '고객센터 운영시간(휴일)',
	`basic_cs_time4` varchar(50) NOT NULL default '' COMMENT '고객센터 운영시간(점심시간)',
	`basic_title` varchar(250) NOT NULL default '' COMMENT '상단 타이틀',
	`basic_description` varchar(250) NOT NULL default '' COMMENT '검색엔진 간략설명',
	`basic_image` varchar(100) NOT NULL default '' COMMENT '대표이미지',
	`basic_keyword` varchar(250) NOT NULL default '' COMMENT '검색엔진 키워드',
	`basic_real_keyword` varchar(250) NOT NULL default '' COMMENT '실시간 검색어',
	`comp_name` varchar(50) NOT NULL default '' COMMENT '상호(회사명)',
	`comp_owner` varchar(50) NOT NULL default '' COMMENT '대표자명',
	`comp_license_no1` varchar(50) NOT NULL default '' COMMENT '사업자등록번호',
	`comp_license_no2` varchar(50) NOT NULL default '' COMMENT '통신판매신고번호',
	`comp_type` varchar(100) NOT NULL default '' COMMENT '업종',
	`comp_item` varchar(100) NOT NULL default '' COMMENT '업태',
	`comp_email` varchar(100) NOT NULL default '' COMMENT '대표이메일 주소',
	`comp_tel` varchar(50) NOT NULL default '' COMMENT '대표전화반호',
	`comp_fax` varchar(50) NOT NULL default '' COMMENT '팩스번호',
	`comp_postcode` varchar(10) NOT NULL default '' COMMENT '사업장 주소 우편번호',
	`comp_address1` varchar(100) NOT NULL default '' COMMENT '사업장 주소',
	`comp_address2` varchar(100) NOT NULL default '' COMMENT '사업장 상세주소',
	`comp_rtn_postcode` varchar(10) NOT NULL default '' COMMENT '교환/반품지 주소 우편번호',
	`comp_rtn_address1` varchar(100) NOT NULL default '' COMMENT '교환/반품지 주소',
	`comp_rtn_address2` varchar(100) NOT NULL default '' COMMENT '교환/반품지 상세주소',
	`payment_type_b` tinyint unsigned NOT NULL default '0' COMMENT '결제 수단 중 무통장입금 사용여부 0(사용안함), 1(사용함)',
	`payment_type_c` tinyint unsigned NOT NULL default '0' COMMENT '결제 수단 중 카드결제 사용여부 0(사용안함), 1(사용함)',
	`payment_type_r` tinyint unsigned NOT NULL default '0' COMMENT '결제 수단 중 실시간계좌이체 사용여부 0(사용안함), 1(사용함)',
	`payment_type_v` tinyint unsigned NOT NULL default '0' COMMENT '결제 수단 중 가상계좌이체 사용여부 0(사용안함), 1(사용함)',
	`payment_type_h` tinyint unsigned NOT NULL default '0' COMMENT '결제 수단 중 핸드폰결제 사용여부 0(사용안함), 1(사용함)',
	`payment_cp` varchar(30) NOT NULL default '' COMMENT '전자결제대행사',
	`payment_shop_id` varchar(50) NOT NULL default '' COMMENT '전자결제대행사 상점아이디',
	`payment_shop_key` varchar(100) NOT NULL default '' COMMENT '전자결제대행사 상점키',
	`payment_install_range` int unsigned NOT NULL default '6' COMMENT '카드 할부기간',
	`payment_escrow_v` tinyint unsigned NOT NULL default '0' COMMENT '에스크로 가상계좌이체 사용여부 0(사용안함), 1(사용함)',
	`payment_complex_tax` tinyint unsigned NOT NULL default '0' COMMENT '복합과세 사용여부 0(사용안함), 1(사용함)',
	`payment_bank_info` text NOT NULL COMMENT '무통장입금은행 정보',
	`payment_commission_c` float(4,2) NOT NULL default '0' COMMENT '결제 대행사 카드결제 수수료율',
	`payment_commission_r` float(4,2) NOT NULL default '0' COMMENT '결제 대행사 계좌이체 수수료울',
	`payment_commission_r2` int unsigned NOT NULL default '0' COMMENT '결제 대행사 계좌이체 최소 수수료',
	`payment_commission_v` int unsigned  NOT NULL default '0' COMMENT '결제 대행사 가상계좌이체 수수료',
	`payment_commission_h` float(4,2) NOT NULL default '0' COMMENT '결제 대행사 핸드폰결제 수수료율',
	`cash_receipts_used` tinyint unsigned NOT NULL default '0' COMMENT '현금영수증 사용여부 0(사용안함), 1(사용함)',
	`cash_receipts_require` tinyint unsigned NOT NULL default '0' COMMENT '현금영수증 필수신청 사용여부 0(사용안함), 1(사용함)',
	`cash_receipts_method` tinyint unsigned NOT NULL default '0' COMMENT '현금영수증 발급 방법 0(관리자직접발급), 1(자동발급)',
	`cash_receipts_type` tinyint unsigned NOT NULL default '0' COMMENT '현금영수증 사업자 형태 0(일반 사업자), 1(면세/간이사업자)',
	`naverpay_used` tinyint unsigned NOT NULL default '0' COMMENT '네이버페이 사용여부 0(사용안함), 1(사용함)',
	`naverpay_mode` tinyint unsigned NOT NULL default '0' COMMENT '네이버페이 모드 0(테스트서버), 1(실서버)',
	`naverpay_test_id` varchar(50) NOT NULL default '' COMMENT '네이버페이 테스트 아이디',
	`naverpay_shop_id` varchar(50) NOT NULL default '' COMMENT '네이버페이 상점 ID',
	`naverpay_key1` varchar(50) NOT NULL default '' COMMENT '네이버페이 가맹점 인증키',
	`naverpay_key2` varchar(50) NOT NULL default '' COMMENT '네이버페이 버튼 인증키',
	`naverpay_key3` varchar(50) NOT NULL default '' COMMENT '네이버 공통 인증키',
	`delivery_type` enum('F','D','P') NOT NULL default 'P' COMMENT '배송비 적용방식 F(무료배송), D(착불), P(조건부 배송비)',
	`delivery_d_price` int unsigned NOT NULL default '0' COMMENT '착불 배송비',
	`delivery_p_type` varchar(20) NOT NULL default 'order' COMMENT '조건부 배송비 최종금액 방식 order(주문금액), pay(결제금액)',
	`delivery_p_price1` int unsigned NOT NULL default '0' COMMENT '조건부 배송비 최종금액 조건',
	`delivery_p_price2` int unsigned NOT NULL default '0' COMMENT '조건부 배송비 부과될 배송비',
	`delivery_info` text NOT NULL COMMENT '배송 업체 정보',
	`member_auth` enum('A','P') NOT NULL default 'A' COMMENT '회원승인방식 A(가입시 자동승인), P(관리자 수동승인)',
	`member_auth_email` int unsigned NOT NULL default '0' COMMENT '아이디, 비밀번호 찾기시 이메일 인증 사용여부',
	`member_auth_cell` int unsigned NOT NULL default '0' COMMENT '아이디, 비밀번호 찾기시 핸드폰 인증 사용여부',
	`member_unavailable_id` text NOT NULL COMMENT '가입불가 아이디 설정',
	`member_mileage_yn` enum('Y','N') NOT NULL default 'Y' COMMENT '마일리지 사용여부 N(사용안함), Y(사용함)',
	`member_mileage_validity_yn` enum('Y','N') NOT NULL default 'N' COMMENT '마일리지 유효기간 사용여부',
	`member_mileage_validity` varchar(100) NOT NULL default '' COMMENT '마일리지 유효기간',
	`member_mileage_validity_type` enum('D','M','Y') NOT NULL default 'Y' COMMENT '마일리지 유효기간 타입',
	`member_mileage_join` int unsigned NOT NULL default '0' COMMENT '회원가입시 지급 마일리지',
	`member_mileage_order` int unsigned NOT NULL default '0' COMMENT '상품구매시 지급 마일리지',
	`member_limit_count` int unsigned NOT NULL default '0' COMMENT '비밀번호 연속실패 횟수',
	`member_limit_minute` int unsigned NOT NULL default '0' COMMENT '로그인 제한 시간(분)',
	`member_admin_auth` enum('N','E','H') NOT NULL default 'N' COMMENT '관리자 로그인 인증 방법',
	`member_login_limit_minute` int unsigned NOT NULL default '0' COMMENT '관리자 로그인 유지시간',
	`member_form_tel` tinyint unsigned NOT NULL default '0' COMMENT '회원가입 항목 전화번호 사용여부',
	`member_form_cell` tinyint unsigned NOT NULL default '0' COMMENT '회원가입 항목 핸드폰번호 사용여부',
	`member_form_address` tinyint unsigned NOT NULL default '0' COMMENT '회원가입 항목 주소 사용여부',
	`member_form_birth` tinyint unsigned NOT NULL default '0' COMMENT '회원가입 항목 생년월일 사용여부',
	`member_form_gender` tinyint unsigned NOT NULL default '0' COMMENT '회원가입 항목 성별 사용여부',
	`member_form_marry` tinyint unsigned NOT NULL default '0' COMMENT '회원가입 항목 결혼여부 사용여부',
	`member_form_job` tinyint unsigned NOT NULL default '0' COMMENT '회원가입 항목 직업 사용여부',
	`member_form_job_info` text NOT NULL COMMENT '회원가입 직업 항목',
	`member_form_hobby` tinyint unsigned NOT NULL default '0' COMMENT '회원가입 항목 관심분야 사용여부',
	`member_form_hobby_info` text NOT NULL COMMENT '회원가입 관심분야 항목',
	`member_form_mailling` tinyint unsigned NOT NULL default '0' COMMENT '정보/이벤트 메일 수신 동의 사용여부',
	`member_form_sms` tinyint unsigned NOT NULL default '0' COMMENT '정보/이벤트 SMS 수신 동의 사용여부',
	`member_form_comp` tinyint unsigned NOT NULL default '0' COMMENT '상호(회사명) 사용여부',
	`member_form_comp_num` tinyint unsigned NOT NULL default '0' COMMENT '사업자번호 사용여부',
	`member_form_comp_owner` tinyint unsigned NOT NULL default '0' COMMENT '대표자명 사용여부',
	`member_form_comp_address` tinyint unsigned NOT NULL default '0' COMMENT '사업장주소 사용여부',
	`member_form_comp_type` tinyint unsigned NOT NULL default '0' COMMENT '업태 사용여부',
	`member_form_comp_item` tinyint unsigned NOT NULL default '0' COMMENT '종목 사용여부',
	`member_form_add1_title` varchar(50) NOT NULL default '' COMMENT '추가항목#1 항목명',
	`member_form_add1` tinyint unsigned NOT NULL default '0' COMMENT '추가항목#1 사용여부',
	`member_form_add2_title` varchar(50) NOT NULL default '' COMMENT '추가항목#2 항목명',
	`member_form_add2` tinyint unsigned NOT NULL default '0' COMMENT '추가항목#2 사용여부',
	`member_form_add3_title` varchar(50) NOT NULL default '' COMMENT '추가항목#3 항목명',
	`member_form_add3` tinyint unsigned NOT NULL default '0' COMMENT '추가항목#3 사용여부',
	`member_form_add4_title` varchar(50) NOT NULL default '' COMMENT '추가항목#4 항목명',
	`member_form_add4` tinyint unsigned NOT NULL default '0' COMMENT '추가항목#4 사용여부',
	`member_form_add5_title` varchar(50) NOT NULL default '' COMMENT '추가항목#5 항목명',
	`member_form_add5` tinyint unsigned NOT NULL default '0' COMMENT '추가항목#5 사용여부',
	`member_level_time` int unsigned NOT NULL default 0 COMMENT '회원등급평가 최종작업시간',
	`member_level_date` varchar(50) NOT NULL default '' COMMENT '회원등급평가 최종작업 조회가간',
	`agreement_info1` text NOT NULL COMMENT '이용약관 내용',
	`agreement_info2` text NOT NULL COMMENT '개인정보취급방침 내용',
	`agreement_info3` text NOT NULL COMMENT '개인정보 수집 및 이용 동의 회원가입시',
	`agreement_info4` text NOT NULL COMMENT '개인정보 수집 및 이용 동의 비회원구매시',
	`agreement_info5` text NOT NULL COMMENT '개인정보 수집 및 이용 동의 비회원글작성시',
	`agreement_info6` text NOT NULL COMMENT '판매이용약관 내용',
	`goods_price_limit1` int unsigned NOT NULL default '0' COMMENT '상품금액 절사 기준 단위',
	`goods_price_limit2` tinyint unsigned NOT NULL default '1' COMMENT '상품금액 절사 기준 처리',
	`goods_soldout` tinyint unsigned NOT NULL default '0' COMMENT '품절상품 설정',
	`goods_engine_naver` tinyint unsigned NOT NULL default '0' COMMENT '네이버 지식쇼핑 연동 여부',
	`goods_engine_daum` tinyint unsigned NOT NULL default '0' COMMENT '다음 쇼핑하우 연동 여부',
	`goods_option_info` text NOT NULL COMMENT '옵션 설정 정보',
	`goods_brand_info` text NOT NULL COMMENT '브랜드 설정 정보',
	`goods_make_info` text NOT NULL COMMENT '제조사 설정 정보',
	`goods_origin_info` text NOT NULL COMMENT '원산지 설정 정보',
	`goods_require_info` text NOT NULL COMMENT '상품 필수정보 설정 정보',
	`goods_icon_info` text NOT NULL COMMENT '아이콘 설정 정보',
	`goods_delivery_info` text NOT NULL COMMENT '이용안내 배송안내 정보',
	`goods_refund_info` text NOT NULL COMMENT '이용안내 환불안내 정보',
	`goods_exchange_info` text NOT NULL COMMENT '이용안내 반품안내 정보',
	`goods_as_info` text NOT NULL COMMENT '이용안내 AS안내 정보',
	`order_cancel_info` text NOT NULL COMMENT '교환/반품/취소사유 설정 정보',
	`order_message_info` text NOT NULL COMMENT '배송요청사항 설정 정보',
	`order_auto_completed1` int unsigned NOT NULL default '0' COMMENT '자동배송완료 설정',
	`order_auto_completed2` int unsigned NOT NULL default '0' COMMENT '자동구매확정 설정',
	`order_auto_completed3` int unsigned NOT NULL default '0' COMMENT '자동주문취소 설정',
	`order_tracker_yn` enum('Y','N') NOT NULL default 'N' COMMENT '스마트택배 API 연동여부',
	`order_tracker_key` varchar(50) NOT NULL default '' COMMENT '스마트택배 API Key',
	`sms_yn` enum('Y','N') NOT NULL default 'Y' COMMENT 'SMS 사용여부',
	`sms_key` varchar(50) NOT NULL default '' COMMENT 'coolSms API Key',
	`sms_secret` varchar(50) NOT NULL default '' COMMENT 'coolSms API Secret',
	`sms_calling_number` varchar(30) NOT NULL default '' COMMENT 'SMS 발신번호',
	`sms_admin_number1` varchar(30) NOT NULL default '' COMMENT 'SMS 관리자번호 #1',
	`sms_admin_number2` varchar(30) NOT NULL default '' COMMENT 'SMS 관리자번호 #2',
	`sms_admin_number3` varchar(30) NOT NULL default '' COMMENT 'SMS 관리자번호 #3',
	`design_skin` varchar(50) NOT NULL default '' COMMENT '사용중인 스킨',
	`design_skin_ing` varchar(50) NOT NULL default '' COMMENT '작업중인 스킨',
	`design_top_menu` text NOT NULL COMMENT '상단메뉴',
	`design_main_display1` tinyint unsigned NOT NULL default '0' COMMENT '메인 인기상품 설정',
	`design_main_display2` tinyint unsigned NOT NULL default '0' COMMENT '메인 추천상품 설정',
	`design_main_display3` tinyint unsigned NOT NULL default '0' COMMENT '메인 신상품 설정',
	`design_main_category` tinyint unsigned NOT NULL default '0' COMMENT '메인 분류상품 설정',
	`design_main_category_info` text NOT NULL COMMENT '메인 분류상품 정보',
	`design_main_custom_code` tinyint unsigned NOT NULL default '0' COMMENT '메인 커스텀코드 설정',
	`design_main_custom_code_image` text NOT NULL COMMENT '커스텀 디자인 이미지',
	`design_main_custom_code_info` text NOT NULL COMMENT '커스텀 디자인',
	`design_main_display_order` text NOT NULL COMMENT '메인 노출순서 설정',
	`design_main2_display1` tinyint unsigned NOT NULL default '0' COMMENT '분류메인 인기상품 설정',
	`design_main2_display2` tinyint unsigned NOT NULL default '0' COMMENT '분류메인 추천상품 설정',
	`design_main2_display3` tinyint unsigned NOT NULL default '0' COMMENT '분류메인 신상품 설정',
	`design_main2_display_order` text NOT NULL COMMENT '분류메인 노출순서 설정',
	`design_icon_display` varchar(20) NOT NULL default '' COMMENT '하단 아이콘 설정',
	`design_vendor_link` tinyint unsigned NOT NULL default '0' COMMENT '하단 입점링크 노출 여부',
	`mobile_yn` enum('Y','N') NOT NULL default 'Y' COMMENT '모바일 사용여부 N(사용안함), Y(사용함)',
	`mobile_icon` varchar(50) NOT NULL default '' COMMENT '모바일 아이콘',
	`mobile_top_menu` text NOT NULL COMMENT '모바일 상단메뉴',
	`inquiry_cate_info` text NOT NULL COMMENT '분류 정보',
	`inquiry_access_write` int unsigned NOT NULL default '0' COMMENT '글쓰기 권한',
	`inquiry_secret_type` int unsigned NOT NULL default '0' COMMENT '비밀글',
	`inquiry_privacy_type` int unsigned NOT NULL default '0' COMMENT '작성자표시보호',
	`push_apiKey` varchar(100) NOT NULL default '' COMMENT 'firebaseConfig apiKey',
	`push_authDomain` varchar(100) NOT NULL default '' COMMENT 'firebaseConfig authDomain',
	`push_projectId` varchar(100) NOT NULL default '' COMMENT 'firebaseConfig projectId',
	`push_storageBucket` varchar(100) NOT NULL default '' COMMENT 'firebaseConfig storageBucket',
	`push_messagingSenderId` varchar(100) NOT NULL default '' COMMENT 'firebaseConfig messagingSenderId',
	`push_appId` varchar(100) NOT NULL default '' COMMENT 'firebaseConfig appId',
	`push_server_key` varchar(200) NOT NULL default '' COMMENT '클라우드 메시징 server_key',
	`push_server_key2` varchar(200) NOT NULL default '' COMMENT '클라우드 메시징 키 쌍',
	`script_naver_tag` varchar(100) NOT NULL default '' COMMENT '네이버메타태그',
	`script_google_analytics` varchar(100) NOT NULL default '' COMMENT '구글통계 추적ID',
	`script_top_code` text NOT NULL COMMENT '상단공통영역스크립트',
	`script_bottom_code` text NOT NULL COMMENT '하단공통영역스크립트',
	`signdate` int unsigned NOT NULL default 0 COMMENT '쇼핑몰 최초 오픈시간',
  PRIMARY KEY  (`uid`)
) DEFAULT CHARSET=utf8 COMMENT='쇼핑몰 환경 설정 정보 (uid=1: 기본, uid=2: 회원/약관, uid=3: 초기화용)';

CREATE TABLE mallRN_exhibition (
  `uid` int unsigned NOT NULL AUTO_INCREMENT COMMENT '고유값',
  `name` varchar(100) NOT NULL default '' COMMENT '모음전 이름',
  `discount_yn` enum('N','Y') NOT NULL default 'Y' COMMENT '할인여부 Y(사용함), N(사용안함)',
  `discount` int unsigned NOT NULL default '0' COMMENT '할인 사용 할 경우 할인률',
  `s_date` datetime default '1000-01-01 00:00:00' COMMENT '할인 시작시간',
  `e_date` datetime default '1000-01-01 00:00:00' COMMENT '할인 종료시간',
  `cate_info` text NOT NULL COMMENT '모음전 분류 정보',
  `image1` varchar(100) NOT NULL default '' COMMENT '모음전 리스트 썸네일 이미지',
  `detail_image` text NOT NULL COMMENT '모음전 설명 이미지',
  `detail_image_only` tinyint unsigned NOT NULL default '0' COMMENT '모음전 설명 방식',
  `detail_image_type` tinyint unsigned NOT NULL default '1' COMMENT '이미지간 출력 방식',
  `explains` text NOT NULL COMMENT '모음전 설명',
  `status` tinyint unsigned NOT NULL default '0' COMMENT '상태 0, 1(준비중), 2(진행중), 3(종료)',
  `signdate` int unsigned NOT NULL default '0' COMMENT '등록일',
  PRIMARY KEY  (`uid`)
) DEFAULT CHARSET=utf8 COMMENT='모음전 정보';

CREATE TABLE mallRN_exhibition_goods (
  `uid` int unsigned NOT NULL AUTO_INCREMENT COMMENT '고유값',
  `euid` int unsigned NOT NULL default '0' COMMENT '모음전고유값',
  `guid` int unsigned NOT NULL default '0' COMMENT '상품고유값',
  `ecate` int unsigned NOT NULL default '0' COMMENT '모음전분류번호',
  `sequence` int unsigned NOT NULL default '99999' COMMENT '노출 순서',
  PRIMARY KEY  (`uid`)
) DEFAULT CHARSET=utf8 COMMENT='모음전 상품';

CREATE TABLE `mallRN_goods` (
	`uid` int unsigned NOT NULL auto_increment COMMENT '고유값 (10,000부터 시작)',
	`re_uid` int unsigned NOT NULL default '99999999' COMMENT 'uid desc 대체',
	`cate` bigint unsigned NOT NULL default '0' COMMENT '상품분류번호',
	`vendor` varchar(50) NOT NULL default '' COMMENT '판매사 아이디',
	`name` varchar(250) NOT NULL default '' COMMENT '상품명',
	`name_code_able` varchar(250) NOT NULL default '' COMMENT '상품명(제한된 html코드 포함가능)',
    `price` int unsigned NOT NULL default '0' COMMENT '판매가',
	`orig_price` int unsigned NOT NULL default '0' COMMENT '매입가(공급가)',
	`consumer_price` int unsigned NOT NULL default '0' COMMENT '소비자가',
	`price_ment` varchar(100) NOT NULL default '' COMMENT '가격대체문구 (입력시 판매중지)',
	`commission_type` tinyint unsigned NOT NULL default '0' COMMENT '상품별 개별 수수료 여부',
	`commission` float(5,2) unsigned NOT NULL default '0' COMMENT '판매사 상품 개별 수수료',
	`image1` varchar(50) NOT NULL default '' COMMENT '상세이미지(대표)',
	`image2` varchar(50) NOT NULL default '' COMMENT '목록이미지',
	`image3` varchar(50) NOT NULL default '' COMMENT '작은목록이미지',
	`other_image` text NOT NULL COMMENT '추가이미지',
	`detail_image` text NOT NULL COMMENT '상세설명 이미지',
	`detail_image_only` tinyint unsigned NOT NULL default '0' COMMENT '상세설명 방식',
	`detail_image_type` tinyint unsigned NOT NULL default '1' COMMENT '이미지간 출력 방식',
    `explains` text NOT NULL COMMENT '상세설명',
	`option_use` tinyint unsigned NOT NULL default '0' COMMENT '상품옵션 사용여부',
	`option_info` text NOT NULL COMMENT '상품옵션 정보 (옵션명|옵션항목|*|옵션명|옵션항목...)',
	`option_soldout` int unsigned NOT NULL default '0' COMMENT '옵션중 품절여부 0(없음), 1(일부있음), 2(품절)',
	`qty_type` tinyint unsigned NOT NULL default '0' COMMENT '재고 타입 0(한정판매), 1(무제한)',
	`qty` int unsigned NOT NULL default '0' COMMENT '재고수량',
	`limit_qty` int unsigned NOT NULL default '0' COMMENT '구매제한수량',
	`require_info` text NOT NULL COMMENT '상품정보 제공고시 정보',
	`display_use` tinyint unsigned NOT NULL default '0' COMMENT '진열상태 0(진열안함), 1(진열함)',
	`sale_use` tinyint unsigned NOT NULL default '0' COMMENT '판매상태 0(판매안함), 1(판매함)',
	`order_priority` tinyint unsigned NOT NULL default '5' COMMENT '진열 우선순위 0~9',
	`main1_display1` tinyint unsigned NOT NULL default '0' COMMENT '메인 인기상품 진열 여부',
	`main1_display2` tinyint unsigned NOT NULL default '0' COMMENT '메인 추천상품 진열 여부',
	`main1_display3` tinyint unsigned NOT NULL default '0' COMMENT '메인 신상품 진열 여부',
	`main2_display1` tinyint unsigned NOT NULL default '0' COMMENT '분류메인 인기상품 진열 여부',
	`main2_display2` tinyint unsigned NOT NULL default '0' COMMENT '분류메인 추천상품 진열 여부',
	`main2_display3` tinyint unsigned NOT NULL default '0' COMMENT '분류메인 신상품 진열 여부',
	`store_display1` tinyint unsigned NOT NULL default '0' COMMENT '판매사 스토어 인기상품 진열 여부',
	`store_display2` tinyint unsigned NOT NULL default '0' COMMENT '판매사 스토어 추천상품 진열 여부',
	`store_display3` tinyint unsigned NOT NULL default '0' COMMENT '판매사 스토어 신상품 진열 여부',
	`main1_display1_sequence` int unsigned NOT NULL default '99999' COMMENT '메인 인기상품 노출 순서',
	`main1_display2_sequence` int unsigned NOT NULL default '99999' COMMENT '메인 추천상품 노출 순서',
	`main1_display3_sequence` int unsigned NOT NULL default '99999' COMMENT '메인 신상품 노출 순서',
	`main2_display1_sequence` int unsigned NOT NULL default '99999' COMMENT '분류메인 인기상품 노출 순서',
	`main2_display2_sequence` int unsigned NOT NULL default '99999' COMMENT '분류메인 추천상품 노출 순서',
	`main2_display3_sequence` int unsigned NOT NULL default '99999' COMMENT '분류메인 신상품 노출 순서',
	`store_display1_sequence` int unsigned NOT NULL default '99999' COMMENT '판매사 스토어 인기상품 노출 순서',
	`store_display2_sequence` int unsigned NOT NULL default '99999' COMMENT '판매사 스토어 추천상품 노출 순서',
	`store_display3_sequence` int unsigned NOT NULL default '99999' COMMENT '판매사 스토어 신상품 노출 순서',
	`icon` varchar(250) NOT NULL default '' COMMENT '아이콘 (아이콘명|아이콘명...)',
	`goods_code` varchar(50) NOT NULL default '' COMMENT '자체상품코드',
	`detail` text NOT NULL COMMENT '상품간략설명',
	`brand` varchar(50) NOT NULL default '' COMMENT '브랜드',
	`make` varchar(50) NOT NULL default '' COMMENT '제조사',
	`origin` varchar(50) NOT NULL default '' COMMENT '원산지',
	`model` varchar(50) NOT NULL default '' COMMENT '모델명',
	`making_info` text NOT NULL COMMENT '추가 제작정보',
	`mileage_type` tinyint unsigned NOT NULL default '1' COMMENT '마일리지 설정',
	`mileage_common` int unsigned NOT NULL default '0' COMMENT '별도설정(회원공통) 마일리지',
	`mileage_level` text NOT NULL COMMENT '별도설정(회원등급별) 마일리지',
	`delivery_type` tinyint unsigned NOT NULL default '1' COMMENT '배송비 설정',
	`delivery_price` int unsigned NOT NULL default '0' COMMENT '별도책정시 배송비',
	`keyword` text NOT NULL COMMENT '검색 키워드',
	`related_goods_type` tinyint unsigned NOT NULL default '0' COMMENT '연관상품 설정',
	`related_goods` varchar(250) NOT NULL default '' COMMENT '직접등록한 연관상품',
	`information_use` tinyint unsigned NOT NULL default '1' COMMENT '이용안내 설정',
	`delivery_info` text NOT NULL COMMENT '이용안내 설정 배송안내',
	`refund_info` text NOT NULL COMMENT '이용안내 설정 환불안내',
	`exchange_info` text NOT NULL COMMENT '이용안내 설정 교환안내',
	`as_info` text NOT NULL COMMENT '이용안내 설정 AS안내',
	`exhibition` text NOT NULL COMMENT '모음전 (,모음전uid,모음전uid,...)',
	`engine_use` tinyint unsigned NOT NULL default '1' COMMENT '상품외부 연동 설정',
	`view_cnt` int unsigned NOT NULL default '0' COMMENT '상품 보기 횟수',
	`order_cnt` int unsigned NOT NULL default '0' COMMENT '상품 주문 횟수',
	`cate_hide` tinyint unsigned NOT NULL default '0' COMMENT '상품분류 노출 상태',
	`vendor_hide` tinyint unsigned NOT NULL default '0' COMMENT '판매사 판매상태에 따른 노출 상태',
	`auth_ck` enum('N','Y') NOT NULL default 'Y' COMMENT '판매사 상품 승인여부 N(미승인), Y(승인)',
	`moddate` int unsigned NOT NULL default '0' COMMENT '수정일',
	`signdate` int unsigned NOT NULL default '0' COMMENT '등록일',
  PRIMARY KEY (`uid`),
  KEY `name` (`name`)
) DEFAULT CHARSET=utf8 COMMENT='상품 상세 정보';

CREATE TABLE `mallRN_goods_cate` (
	`uid` int unsigned NOT NULL auto_increment COMMENT '고유값',
	`guid` int unsigned NOT NULL default '0' COMMENT '상품고유값',
	`cate` bigint unsigned NOT NULL default '0' COMMENT '상품분류번호',
	`cate_rep` tinyint unsigned NOT NULL default '0' COMMENT '대표분류 여부',
	`sequence` int unsigned NOT NULL default '0' COMMENT '노출 순서',
	`sequence1` int unsigned NOT NULL default '99999' COMMENT '1차분류 리스트 노출 순서',
	`sequence2` int unsigned NOT NULL default '99999' COMMENT '2차분류 리스트 노출 순서',
	`sequence3` int unsigned NOT NULL default '99999' COMMENT '3차분류 리스트 노출 순서',
	`sequence4` int unsigned NOT NULL default '99999' COMMENT '4차분류 리스트 노출 순서',
	PRIMARY KEY  (`uid`),
	KEY `guid` (`guid`)
) DEFAULT CHARSET=utf8 COMMENT='상품 선택된 분류 정보';

CREATE TABLE mallRN_goods_option (
  `uid` int unsigned NOT NULL auto_increment COMMENT '고유값',
  `guid` int unsigned NOT NULL default '0' COMMENT '상품고유값',
  `value` varchar(250) NOT NULL default '' COMMENT '옵션명',
  `price` int NOT NULL default '0' COMMENT '추가금액',
  `qty_type` tinyint unsigned NOT NULL default '0' COMMENT '재고 타입',
  `qty` int unsigned NOT NULL default '0' COMMENT '재고 수량',
  `used` tinyint unsigned NOT NULL default '0' COMMENT '노출 여부',
  `code` varchar(100) NOT NULL default '' COMMENT '자체품목코드',
  `sequence` int unsigned NOT NULL default '0' COMMENT '노출 순서',
  PRIMARY KEY  (`uid`)
) DEFAULT CHARSET=utf8 COMMENT='상품 옵션 정보';

CREATE TABLE mallRN_popup (
  `uid` int unsigned NOT NULL AUTO_INCREMENT COMMENT '고유값',
  `name` varchar(80) NOT NULL default '' COMMENT '팝업명',
  `status` int unsigned NOT NULL default '0' COMMENT '상태 0(사용), 1(사용안함), 2(기간종료)',
  `type` int unsigned NOT NULL default '0' COMMENT '형태 0(항상), 1(하루에 한번)',
  `period` int unsigned NOT NULL default '0' COMMENT '기간 0(무기한), 1(특정기간)',
  `s_date` datetime default '1000-01-01 00:00:00' COMMENT '팝업 시작시간',
  `e_date` datetime default '1000-01-01 00:00:00' COMMENT '팝업 종료시간',
  `position` int unsigned NOT NULL default '0' COMMENT '위치',
  `input_position` varchar(50) NOT NULL default '' COMMENT '입력위치',
  `input_size` varchar(50) NOT NULL default '' COMMENT '창사이즈',
  `image_only` tinyint unsigned NOT NULL default '0' COMMENT '방식 0(웹에디터), 1(이미지)',
  `image1` varchar(100) NOT NULL default '' COMMENT '이미지',
  `link1` varchar(250) NOT NULL default '' COMMENT '이동 url',
  `content` text NOT NULL COMMENT '내용',
  `signdate` int unsigned NOT NULL default '0' COMMENT '등록일시',
  PRIMARY KEY (`uid`)
) DEFAULT CHARSET=utf8 COMMENT='팝업 정보';
