CREATE TABLE `mallRN_order_cash_receipts` (
  `uid` int unsigned NOT NULL AUTO_INCREMENT,
  `order_num` varchar(32) NOT NULL DEFAULT '',
  `id` varchar(50) NOT NULL DEFAULT '',
  `name` varchar(50) NOT NULL DEFAULT '',
  `cell` varchar(30) NOT NULL DEFAULT '',
  `email` varchar(80) NOT NULL DEFAULT '',
  `price` int unsigned NOT NULL DEFAULT 0,
  `partial_price` int unsigned NOT NULL DEFAULT 0,
  `goods_name` varchar(250) NOT NULL DEFAULT '',
  `pay_type` enum('B','C','R','V','H','M') NOT NULL DEFAULT 'B',
  `tax_type` int unsigned NOT NULL DEFAULT 0,
  `cash_type` int unsigned NOT NULL DEFAULT 0,
  `auth_number` varchar(30) NOT NULL DEFAULT '',
  `receipt_time` varchar(30) NOT NULL DEFAULT '',
  `receipt_no` varchar(50) NOT NULL DEFAULT '',
  `receipt_cancel_no` varchar(50) NOT NULL DEFAULT '',
  `receipt_info` varchar(100) NOT NULL DEFAULT '',
  `receipt_status` varchar(20) NOT NULL DEFAULT '',
  `receipt_error` varchar(250) NOT NULL DEFAULT '',
  `status` int unsigned NOT NULL DEFAULT 0,
  `status_date` int unsigned NOT NULL DEFAULT 0,
  `signdate` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`uid`),
  KEY `order_num` (`order_num`)
) DEFAULT CHARSET=utf8mb4 COMMENT='현금영수증발급정보';
