CREATE TABLE IF NOT EXISTS `mallRN_order_status_change` (
  `uid` int unsigned NOT NULL AUTO_INCREMENT,
  `id` varchar(50) NOT NULL default '',
  `name` varchar(50) NOT NULL default '',
  `manager` varchar(50) NOT NULL default '',
  `vendor` varchar(50) NOT NULL default '',
  `order_num` varchar(32) NOT NULL default '',
  `og_uid` int unsigned NOT NULL default '0',
  `reason` varchar(100) NOT NULL default '',
  `bank_info` varchar(250) NOT NULL default '',
  `message` text,
  `refund` int unsigned NOT NULL default '0',
  `delivery` int unsigned NOT NULL default '0',
  `delivery2` int unsigned NOT NULL default '0',
  `mileage` int unsigned NOT NULL default '0',
  `coupon` int unsigned NOT NULL default '0',
  `refund_fee` int unsigned NOT NULL default '0',
  `status` tinyint unsigned NOT NULL default '9',
  `status2` tinyint unsigned NOT NULL default '1',
  `status_date` int unsigned NOT NULL default '0',
  `signdate` int unsigned NOT NULL default '0',
  PRIMARY KEY (`uid`),
  KEY `idx_order_status_change_order` (`order_num`),
  KEY `idx_order_status_change_vendor` (`vendor`,`status`,`status2`)
) DEFAULT CHARSET=utf8mb4 COMMENT='교환/반품/취소요청';
