import { readFile } from "node:fs/promises";
import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import { vendorDocPath } from "@/lib/vendor-doc-upload";

const CONTENT_TYPES: Record<string, string> = {
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  png: "image/png",
  gif: "image/gif",
  webp: "image/webp",
  pdf: "application/pdf",
};

// Gated read side of vendor-doc-upload.ts — a vendor may only fetch their
// own documents, an admin may fetch any vendor's. No public path exists for
// these files (unlike product/banner images), matching the PII they hold.
export async function GET(_request: Request, { params }: { params: Promise<{ vendorId: string; filename: string }> }): Promise<NextResponse> {
  const { vendorId, filename } = await params;
  const session = await getSession();
  if (!session) return new NextResponse("", { status: 401 });
  if (session.role === "vendor" && session.vendorId !== vendorId) return new NextResponse("", { status: 403 });
  if (session.role !== "admin" && session.role !== "vendor") return new NextResponse("", { status: 403 });

  // filename comes from a route param already generated by crypto.randomUUID()
  // at upload time (vendor-doc-upload.ts) — reject anything else outright
  // rather than letting path.join near user input.
  if (!/^[0-9a-f-]+\.[a-z0-9]+$/i.test(filename)) return new NextResponse("", { status: 400 });

  try {
    const buffer = await readFile(vendorDocPath(vendorId, filename));
    const ext = filename.split(".").pop()?.toLowerCase() ?? "";
    return new NextResponse(new Uint8Array(buffer), { headers: { "Content-Type": CONTENT_TYPES[ext] ?? "application/octet-stream" } });
  } catch {
    return new NextResponse("", { status: 404 });
  }
}
